version: "3.8"

services:
  grobid:
    image: lfoppiano/grobid:0.8.1
    container_name: grobid_service
    ports:
      - "8070:8070"
    restart: always
    init: true
    ulimits:
      core: 0
  provenance_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: provenance_service
    command: ["python", "provenance/create_prov.py"]
    depends_on:
      - grobid